SELECT
    EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH,
    GENDER, 
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM 
    USER_INFO A, ONLINE_SALE B
WHERE
    A.USER_ID = B.USER_ID AND
    GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM B.SALES_DATE),
    EXTRACT(MONTH FROM B.SALES_DATE),
    GENDER
HAVING 
    GENDER IS NOT NULL
ORDER BY
    1, 2, 3