SELECT 
    USER_ID, NICKNAME, TOTAL_SALES
FROM 
    (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
     FROM USED_GOODS_BOARD
     WHERE STATUS LIKE ('DONE')
     GROUP BY WRITER_ID) A,
     USED_GOODS_USER B
WHERE 
    WRITER_ID = USER_ID AND
    TOTAL_SALES >= 700000
ORDER BY 3
