SELECT 
    A.MEMBER_NAME, 
    B.REVIEW_TEXT,
    TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE A, REST_REVIEW B
WHERE
    A.MEMBER_ID = B.MEMBER_ID AND
    A.MEMBER_ID = (SELECT MEMBER_ID
                   FROM REST_REVIEW
                   GROUP BY MEMBER_ID
                   ORDER BY COUNT(REVIEW_ID) DESC
                   FETCH FIRST 1 ROWS ONLY)
ORDER BY 3, 2