WITH B AS ( 
    SELECT 
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD') AND
        START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
    GROUP BY
        CAR_ID
    HAVING 
        COUNT(*) >= 5
)


SELECT 
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    A.CAR_ID,
    COUNT(A.CAR_ID) AS RECORDS
FROM
   CAR_RENTAL_COMPANY_RENTAL_HISTORY A, 
   B
WHERE 
    A.CAR_ID = B.CAR_ID AND 
    START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD') AND
    START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
GROUP BY
    EXTRACT (MONTH FROM A.START_DATE), A.CAR_ID
ORDER BY 
    1, 2 DESC